# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'GUI.ui'
##
## Created by: Qt User Interface Compiler version 6.7.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QAbstractSpinBox, QApplication, QDial, QFrame,
    QLCDNumber, QLabel, QListWidget, QListWidgetItem,
    QMainWindow, QProgressBar, QPushButton, QRadioButton,
    QSizePolicy, QSpinBox, QStatusBar, QTabWidget,
    QTextBrowser, QWidget)
import Injection_rc
import Eau_rc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1920, 1080)
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setEnabled(True)
        self.tabWidget.setGeometry(QRect(0, 0, 1891, 821))
        self.tabWidget.setTabShape(QTabWidget.TabShape.Rounded)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setTabBarAutoHide(False)
        self.Injection = QWidget()
        self.Injection.setObjectName(u"Injection")
        self.label_2 = QLabel(self.Injection)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(620, 130, 598, 519))
        self.label_2.setPixmap(QPixmap(u":/newPrefix/Schema Injection.png"))
        self.Container_Injection_General = QWidget(self.Injection)
        self.Container_Injection_General.setObjectName(u"Container_Injection_General")
        self.Container_Injection_General.setGeometry(QRect(10, 670, 303, 111))
        self.frame_12 = QFrame(self.Container_Injection_General)
        self.frame_12.setObjectName(u"frame_12")
        self.frame_12.setGeometry(QRect(0, 20, 303, 91))
        self.frame_12.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame_12.setFrameShadow(QFrame.Shadow.Raised)
        self.afficheur_14 = QWidget(self.frame_12)
        self.afficheur_14.setObjectName(u"afficheur_14")
        self.afficheur_14.setGeometry(QRect(20, 10, 171, 61))
        self.label_37 = QLabel(self.afficheur_14)
        self.label_37.setObjectName(u"label_37")
        self.label_37.setGeometry(QRect(0, 0, 65, 16))
        self.label_38 = QLabel(self.afficheur_14)
        self.label_38.setObjectName(u"label_38")
        self.label_38.setGeometry(QRect(130, 40, 41, 16))
        self.lcdNumber_DebitArgon = QLCDNumber(self.afficheur_14)
        self.lcdNumber_DebitArgon.setObjectName(u"lcdNumber_DebitArgon")
        self.lcdNumber_DebitArgon.setGeometry(QRect(0, 20, 121, 41))
        self.lcdNumber_DebitArgon.setSmallDecimalPoint(False)
        self.afficheur_15 = QWidget(self.frame_12)
        self.afficheur_15.setObjectName(u"afficheur_15")
        self.afficheur_15.setGeometry(QRect(200, 30, 83, 44))
        self.label_39 = QLabel(self.afficheur_15)
        self.label_39.setObjectName(u"label_39")
        self.label_39.setGeometry(QRect(0, 0, 66, 16))
        self.pushButton_Diaphragme = QPushButton(self.afficheur_15)
        self.pushButton_Diaphragme.setObjectName(u"pushButton_Diaphragme")
        self.pushButton_Diaphragme.setGeometry(QRect(0, 20, 75, 24))
        self.pushButton_Diaphragme.setCheckable(True)
        self.pushButton_Diaphragme.setChecked(True)
        self.label_59 = QLabel(self.Container_Injection_General)
        self.label_59.setObjectName(u"label_59")
        self.label_59.setGeometry(QRect(0, 0, 41, 16))
        self.Container_5 = QWidget(self.Injection)
        self.Container_5.setObjectName(u"Container_5")
        self.Container_5.setGeometry(QRect(40, 180, 471, 351))
        self.frame_6 = QFrame(self.Container_5)
        self.frame_6.setObjectName(u"frame_6")
        self.frame_6.setGeometry(QRect(0, 20, 471, 331))
        self.frame_6.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame_6.setFrameShadow(QFrame.Shadow.Raised)
        self.label_26 = QLabel(self.frame_6)
        self.label_26.setObjectName(u"label_26")
        self.label_26.setGeometry(QRect(10, 10, 64, 16))
        self.radioButton_C1S1_2 = QRadioButton(self.frame_6)
        self.radioButton_C1S1_2.setObjectName(u"radioButton_C1S1_2")
        self.radioButton_C1S1_2.setGeometry(QRect(10, 60, 92, 20))
        self.radioButton_C1S2_2 = QRadioButton(self.frame_6)
        self.radioButton_C1S2_2.setObjectName(u"radioButton_C1S2_2")
        self.radioButton_C1S2_2.setGeometry(QRect(10, 130, 92, 20))
        self.afficheur_20 = QWidget(self.frame_6)
        self.afficheur_20.setObjectName(u"afficheur_20")
        self.afficheur_20.setGeometry(QRect(100, 120, 149, 41))
        self.label_66 = QLabel(self.afficheur_20)
        self.label_66.setObjectName(u"label_66")
        self.label_66.setGeometry(QRect(130, 10, 19, 16))
        self.spinBox_RayonCanneC2_3 = QSpinBox(self.afficheur_20)
        self.spinBox_RayonCanneC2_3.setObjectName(u"spinBox_RayonCanneC2_3")
        self.spinBox_RayonCanneC2_3.setEnabled(False)
        self.spinBox_RayonCanneC2_3.setGeometry(QRect(0, 0, 121, 41))
        self.spinBox_RayonCanneC2_3.setButtonSymbols(QAbstractSpinBox.ButtonSymbols.UpDownArrows)
        self.afficheur_21 = QWidget(self.frame_6)
        self.afficheur_21.setObjectName(u"afficheur_21")
        self.afficheur_21.setGeometry(QRect(100, 50, 149, 41))
        self.label_67 = QLabel(self.afficheur_21)
        self.label_67.setObjectName(u"label_67")
        self.label_67.setGeometry(QRect(130, 10, 19, 16))
        self.spinBox_RayonCanneC2_4 = QSpinBox(self.afficheur_21)
        self.spinBox_RayonCanneC2_4.setObjectName(u"spinBox_RayonCanneC2_4")
        self.spinBox_RayonCanneC2_4.setGeometry(QRect(0, 0, 121, 41))
        self.spinBox_RayonCanneC2_4.setButtonSymbols(QAbstractSpinBox.ButtonSymbols.UpDownArrows)
        self.afficheur_16 = QWidget(self.frame_6)
        self.afficheur_16.setObjectName(u"afficheur_16")
        self.afficheur_16.setGeometry(QRect(300, 30, 161, 61))
        self.label_40 = QLabel(self.afficheur_16)
        self.label_40.setObjectName(u"label_40")
        self.label_40.setGeometry(QRect(0, 0, 109, 16))
        self.label_41 = QLabel(self.afficheur_16)
        self.label_41.setObjectName(u"label_41")
        self.label_41.setGeometry(QRect(130, 40, 31, 16))
        self.lcdNumber_15 = QLCDNumber(self.afficheur_16)
        self.lcdNumber_15.setObjectName(u"lcdNumber_15")
        self.lcdNumber_15.setGeometry(QRect(0, 20, 121, 41))
        self.lcdNumber_15.setSmallDecimalPoint(False)
        self.afficheur_17 = QWidget(self.frame_6)
        self.afficheur_17.setObjectName(u"afficheur_17")
        self.afficheur_17.setGeometry(QRect(300, 100, 161, 61))
        self.label_42 = QLabel(self.afficheur_17)
        self.label_42.setObjectName(u"label_42")
        self.label_42.setGeometry(QRect(0, 0, 103, 16))
        self.label_60 = QLabel(self.afficheur_17)
        self.label_60.setObjectName(u"label_60")
        self.label_60.setGeometry(QRect(130, 40, 31, 16))
        self.lcdNumber_16 = QLCDNumber(self.afficheur_17)
        self.lcdNumber_16.setObjectName(u"lcdNumber_16")
        self.lcdNumber_16.setGeometry(QRect(0, 20, 121, 41))
        self.lcdNumber_16.setSmallDecimalPoint(False)
        self.dial_DebitGaz = QDial(self.frame_6)
        self.dial_DebitGaz.setObjectName(u"dial_DebitGaz")
        self.dial_DebitGaz.setGeometry(QRect(310, 190, 71, 81))
        self.label_27 = QLabel(self.frame_6)
        self.label_27.setObjectName(u"label_27")
        self.label_27.setGeometry(QRect(310, 260, 71, 41))
        self.label_27.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.label_27.setAutoFillBackground(False)
        self.label_27.setScaledContents(False)
        self.label_27.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_27.setWordWrap(True)
        self.afficheur_18 = QWidget(self.frame_6)
        self.afficheur_18.setObjectName(u"afficheur_18")
        self.afficheur_18.setGeometry(QRect(60, 250, 161, 61))
        self.label_61 = QLabel(self.afficheur_18)
        self.label_61.setObjectName(u"label_61")
        self.label_61.setGeometry(QRect(0, 0, 131, 16))
        self.label_62 = QLabel(self.afficheur_18)
        self.label_62.setObjectName(u"label_62")
        self.label_62.setGeometry(QRect(130, 40, 31, 16))
        self.lcdNumber_CourantEffFilament = QLCDNumber(self.afficheur_18)
        self.lcdNumber_CourantEffFilament.setObjectName(u"lcdNumber_CourantEffFilament")
        self.lcdNumber_CourantEffFilament.setGeometry(QRect(0, 20, 121, 41))
        self.lcdNumber_CourantEffFilament.setSmallDecimalPoint(False)
        self.numInput_8 = QWidget(self.frame_6)
        self.numInput_8.setObjectName(u"numInput_8")
        self.numInput_8.setGeometry(QRect(60, 180, 145, 61))
        self.label_68 = QLabel(self.numInput_8)
        self.label_68.setObjectName(u"label_68")
        self.label_68.setGeometry(QRect(0, 0, 91, 16))
        self.spinBox_CourantFilament = QSpinBox(self.numInput_8)
        self.spinBox_CourantFilament.setObjectName(u"spinBox_CourantFilament")
        self.spinBox_CourantFilament.setGeometry(QRect(0, 20, 121, 41))
        self.spinBox_CourantFilament.setButtonSymbols(QAbstractSpinBox.ButtonSymbols.UpDownArrows)
        self.label_69 = QLabel(self.numInput_8)
        self.label_69.setObjectName(u"label_69")
        self.label_69.setGeometry(QRect(130, 40, 15, 16))
        self.label_64 = QLabel(self.Container_5)
        self.label_64.setObjectName(u"label_64")
        self.label_64.setGeometry(QRect(0, 0, 37, 16))
        self.tabWidget.addTab(self.Injection, "")
        self.Aimant = QWidget()
        self.Aimant.setObjectName(u"Aimant")
        self.Container_2 = QWidget(self.Aimant)
        self.Container_2.setObjectName(u"Container_2")
        self.Container_2.setGeometry(QRect(20, 20, 341, 111))
        self.frame_2 = QFrame(self.Container_2)
        self.frame_2.setObjectName(u"frame_2")
        self.frame_2.setGeometry(QRect(0, 20, 341, 91))
        self.frame_2.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QFrame.Shadow.Raised)
        self.numInput_3 = QWidget(self.frame_2)
        self.numInput_3.setObjectName(u"numInput_3")
        self.numInput_3.setGeometry(QRect(10, 10, 145, 61))
        self.label_4 = QLabel(self.numInput_3)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(0, 0, 83, 16))
        self.spinBox = QSpinBox(self.numInput_3)
        self.spinBox.setObjectName(u"spinBox")
        self.spinBox.setGeometry(QRect(0, 20, 121, 41))
        self.spinBox.setButtonSymbols(QAbstractSpinBox.ButtonSymbols.UpDownArrows)
        self.label_5 = QLabel(self.numInput_3)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(130, 40, 15, 16))
        self.afficheur = QWidget(self.frame_2)
        self.afficheur.setObjectName(u"afficheur")
        self.afficheur.setGeometry(QRect(180, 10, 145, 61))
        self.label_6 = QLabel(self.afficheur)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(0, 0, 83, 16))
        self.label_7 = QLabel(self.afficheur)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(130, 40, 15, 16))
        self.lcdNumber = QLCDNumber(self.afficheur)
        self.lcdNumber.setObjectName(u"lcdNumber")
        self.lcdNumber.setGeometry(QRect(0, 20, 121, 41))
        self.lcdNumber.setSmallDecimalPoint(False)
        self.label_3 = QLabel(self.Container_2)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(0, 0, 161, 16))
        self.listWidget_magnet = QListWidget(self.Aimant)
        self.listWidget_magnet.setObjectName(u"listWidget_magnet")
        self.listWidget_magnet.setGeometry(QRect(20, 180, 1221, 521))
        self.listWidget_magnet.setFrameShape(QFrame.Shape.Box)
        self.tabWidget.addTab(self.Aimant, "")
        self.RF = QWidget()
        self.RF.setObjectName(u"RF")
        self.Container_3 = QWidget(self.RF)
        self.Container_3.setObjectName(u"Container_3")
        self.Container_3.setGeometry(QRect(20, 20, 441, 181))
        self.frame_3 = QFrame(self.Container_3)
        self.frame_3.setObjectName(u"frame_3")
        self.frame_3.setGeometry(QRect(0, 20, 441, 161))
        self.frame_3.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QFrame.Shadow.Raised)
        self.numInput_4 = QWidget(self.frame_3)
        self.numInput_4.setObjectName(u"numInput_4")
        self.numInput_4.setGeometry(QRect(10, 10, 145, 61))
        self.label_8 = QLabel(self.numInput_4)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(0, 0, 71, 16))
        self.spinBox_2 = QSpinBox(self.numInput_4)
        self.spinBox_2.setObjectName(u"spinBox_2")
        self.spinBox_2.setGeometry(QRect(0, 20, 121, 41))
        self.spinBox_2.setButtonSymbols(QAbstractSpinBox.ButtonSymbols.UpDownArrows)
        self.label_9 = QLabel(self.numInput_4)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(130, 40, 15, 16))
        self.numInput_5 = QWidget(self.frame_3)
        self.numInput_5.setObjectName(u"numInput_5")
        self.numInput_5.setGeometry(QRect(10, 90, 145, 61))
        self.label_10 = QLabel(self.numInput_5)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(0, 0, 70, 16))
        self.spinBox_3 = QSpinBox(self.numInput_5)
        self.spinBox_3.setObjectName(u"spinBox_3")
        self.spinBox_3.setGeometry(QRect(0, 20, 121, 41))
        self.spinBox_3.setButtonSymbols(QAbstractSpinBox.ButtonSymbols.UpDownArrows)
        self.label_11 = QLabel(self.numInput_5)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(130, 40, 15, 16))
        self.label_13 = QLabel(self.frame_3)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(220, 20, 101, 41))
        self.label_13.setAutoFillBackground(False)
        self.label_13.setScaledContents(False)
        self.label_13.setWordWrap(True)
        self.dial = QDial(self.frame_3)
        self.dial.setObjectName(u"dial")
        self.dial.setGeometry(QRect(350, 30, 71, 81))
        self.label_14 = QLabel(self.frame_3)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(340, 110, 91, 41))
        self.label_14.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.label_14.setAutoFillBackground(False)
        self.label_14.setScaledContents(False)
        self.label_14.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_14.setWordWrap(True)
        self.progressBar = QProgressBar(self.frame_3)
        self.progressBar.setObjectName(u"progressBar")
        self.progressBar.setGeometry(QRect(190, 26, 24, 121))
        self.progressBar.setAcceptDrops(False)
        self.progressBar.setValue(24)
        self.progressBar.setTextVisible(False)
        self.progressBar.setOrientation(Qt.Orientation.Vertical)
        self.progressBar.setTextDirection(QProgressBar.Direction.BottomToTop)
        self.label_12 = QLabel(self.Container_3)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(0, 0, 161, 16))
        self.tabWidget.addTab(self.RF, "")
        self.Exxtraction = QWidget()
        self.Exxtraction.setObjectName(u"Exxtraction")
        self.Container_4 = QWidget(self.Exxtraction)
        self.Container_4.setObjectName(u"Container_4")
        self.Container_4.setGeometry(QRect(20, 20, 551, 281))
        self.frame_4 = QFrame(self.Container_4)
        self.frame_4.setObjectName(u"frame_4")
        self.frame_4.setGeometry(QRect(0, 20, 551, 261))
        self.frame_4.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame_4.setFrameShadow(QFrame.Shadow.Raised)
        self.label_19 = QLabel(self.frame_4)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(10, 10, 37, 16))
        self.label_20 = QLabel(self.frame_4)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(300, 10, 37, 16))
        self.radioButton_C1S1 = QRadioButton(self.frame_4)
        self.radioButton_C1S1.setObjectName(u"radioButton_C1S1")
        self.radioButton_C1S1.setGeometry(QRect(10, 40, 92, 20))
        self.radioButton_C1S2 = QRadioButton(self.frame_4)
        self.radioButton_C1S2.setObjectName(u"radioButton_C1S2")
        self.radioButton_C1S2.setGeometry(QRect(10, 80, 92, 20))
        self.radioButton_C1S3 = QRadioButton(self.frame_4)
        self.radioButton_C1S3.setObjectName(u"radioButton_C1S3")
        self.radioButton_C1S3.setGeometry(QRect(10, 120, 92, 20))
        self.numInput_6 = QWidget(self.frame_4)
        self.numInput_6.setObjectName(u"numInput_6")
        self.numInput_6.setGeometry(QRect(10, 160, 145, 91))
        self.label_15 = QLabel(self.numInput_6)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(0, 20, 71, 31))
        self.label_15.setWordWrap(True)
        self.spinBox_RayonCanneC1 = QSpinBox(self.numInput_6)
        self.spinBox_RayonCanneC1.setObjectName(u"spinBox_RayonCanneC1")
        self.spinBox_RayonCanneC1.setGeometry(QRect(0, 50, 121, 41))
        self.spinBox_RayonCanneC1.setButtonSymbols(QAbstractSpinBox.ButtonSymbols.UpDownArrows)
        self.label_16 = QLabel(self.numInput_6)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(130, 70, 15, 16))
        self.numInput_7 = QWidget(self.frame_4)
        self.numInput_7.setObjectName(u"numInput_7")
        self.numInput_7.setGeometry(QRect(300, 160, 145, 91))
        self.label_17 = QLabel(self.numInput_7)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(0, 20, 71, 31))
        self.label_17.setWordWrap(True)
        self.spinBox_RayonCanneC2 = QSpinBox(self.numInput_7)
        self.spinBox_RayonCanneC2.setObjectName(u"spinBox_RayonCanneC2")
        self.spinBox_RayonCanneC2.setGeometry(QRect(0, 50, 121, 41))
        self.spinBox_RayonCanneC2.setButtonSymbols(QAbstractSpinBox.ButtonSymbols.UpDownArrows)
        self.label_18 = QLabel(self.numInput_7)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(130, 70, 15, 16))
        self.radioButton_C2S1 = QRadioButton(self.frame_4)
        self.radioButton_C2S1.setObjectName(u"radioButton_C2S1")
        self.radioButton_C2S1.setGeometry(QRect(300, 40, 92, 20))
        self.radioButton_C2S2 = QRadioButton(self.frame_4)
        self.radioButton_C2S2.setObjectName(u"radioButton_C2S2")
        self.radioButton_C2S2.setGeometry(QRect(300, 80, 92, 20))
        self.radioButton_C2S3 = QRadioButton(self.frame_4)
        self.radioButton_C2S3.setObjectName(u"radioButton_C2S3")
        self.radioButton_C2S3.setGeometry(QRect(300, 120, 92, 20))
        self.afficheur_7 = QWidget(self.frame_4)
        self.afficheur_7.setObjectName(u"afficheur_7")
        self.afficheur_7.setGeometry(QRect(390, 40, 145, 31))
        self.label_48 = QLabel(self.afficheur_7)
        self.label_48.setObjectName(u"label_48")
        self.label_48.setGeometry(QRect(130, 10, 15, 16))
        self.lcdNumber_7 = QLCDNumber(self.afficheur_7)
        self.lcdNumber_7.setObjectName(u"lcdNumber_7")
        self.lcdNumber_7.setGeometry(QRect(0, 0, 111, 31))
        self.lcdNumber_7.setSmallDecimalPoint(False)
        self.afficheur_8 = QWidget(self.frame_4)
        self.afficheur_8.setObjectName(u"afficheur_8")
        self.afficheur_8.setGeometry(QRect(390, 80, 145, 31))
        self.label_49 = QLabel(self.afficheur_8)
        self.label_49.setObjectName(u"label_49")
        self.label_49.setGeometry(QRect(130, 10, 15, 16))
        self.lcdNumber_8 = QLCDNumber(self.afficheur_8)
        self.lcdNumber_8.setObjectName(u"lcdNumber_8")
        self.lcdNumber_8.setGeometry(QRect(0, 0, 111, 31))
        self.lcdNumber_8.setSmallDecimalPoint(False)
        self.afficheur_9 = QWidget(self.frame_4)
        self.afficheur_9.setObjectName(u"afficheur_9")
        self.afficheur_9.setGeometry(QRect(390, 120, 145, 31))
        self.label_50 = QLabel(self.afficheur_9)
        self.label_50.setObjectName(u"label_50")
        self.label_50.setGeometry(QRect(130, 10, 15, 16))
        self.lcdNumber_9 = QLCDNumber(self.afficheur_9)
        self.lcdNumber_9.setObjectName(u"lcdNumber_9")
        self.lcdNumber_9.setGeometry(QRect(0, 0, 111, 31))
        self.lcdNumber_9.setSmallDecimalPoint(False)
        self.afficheur_4 = QWidget(self.frame_4)
        self.afficheur_4.setObjectName(u"afficheur_4")
        self.afficheur_4.setGeometry(QRect(100, 40, 145, 31))
        self.label_45 = QLabel(self.afficheur_4)
        self.label_45.setObjectName(u"label_45")
        self.label_45.setGeometry(QRect(130, 10, 15, 16))
        self.lcdNumber_4 = QLCDNumber(self.afficheur_4)
        self.lcdNumber_4.setObjectName(u"lcdNumber_4")
        self.lcdNumber_4.setGeometry(QRect(0, 0, 111, 31))
        self.lcdNumber_4.setSmallDecimalPoint(False)
        self.afficheur_5 = QWidget(self.frame_4)
        self.afficheur_5.setObjectName(u"afficheur_5")
        self.afficheur_5.setGeometry(QRect(100, 80, 145, 31))
        self.label_46 = QLabel(self.afficheur_5)
        self.label_46.setObjectName(u"label_46")
        self.label_46.setGeometry(QRect(130, 10, 15, 16))
        self.lcdNumber_5 = QLCDNumber(self.afficheur_5)
        self.lcdNumber_5.setObjectName(u"lcdNumber_5")
        self.lcdNumber_5.setGeometry(QRect(0, 0, 111, 31))
        self.lcdNumber_5.setAutoFillBackground(False)
        self.lcdNumber_5.setSmallDecimalPoint(False)
        self.afficheur_6 = QWidget(self.frame_4)
        self.afficheur_6.setObjectName(u"afficheur_6")
        self.afficheur_6.setGeometry(QRect(100, 120, 145, 31))
        self.label_47 = QLabel(self.afficheur_6)
        self.label_47.setObjectName(u"label_47")
        self.label_47.setGeometry(QRect(130, 10, 15, 16))
        self.lcdNumber_6 = QLCDNumber(self.afficheur_6)
        self.lcdNumber_6.setObjectName(u"lcdNumber_6")
        self.lcdNumber_6.setGeometry(QRect(0, 0, 111, 31))
        self.lcdNumber_6.setSmallDecimalPoint(False)
        self.label_21 = QLabel(self.Container_4)
        self.label_21.setObjectName(u"label_21")
        self.label_21.setGeometry(QRect(0, 0, 161, 16))
        self.tabWidget.addTab(self.Exxtraction, "")
        self.Vide = QWidget()
        self.Vide.setObjectName(u"Vide")
        self.Container_8 = QWidget(self.Vide)
        self.Container_8.setObjectName(u"Container_8")
        self.Container_8.setGeometry(QRect(20, 20, 381, 111))
        self.frame_9 = QFrame(self.Container_8)
        self.frame_9.setObjectName(u"frame_9")
        self.frame_9.setGeometry(QRect(0, 20, 381, 91))
        self.frame_9.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame_9.setFrameShadow(QFrame.Shadow.Raised)
        self.afficheur_2 = QWidget(self.frame_9)
        self.afficheur_2.setObjectName(u"afficheur_2")
        self.afficheur_2.setGeometry(QRect(20, 10, 161, 61))
        self.label_24 = QLabel(self.afficheur_2)
        self.label_24.setObjectName(u"label_24")
        self.label_24.setGeometry(QRect(0, 0, 83, 16))
        self.label_25 = QLabel(self.afficheur_2)
        self.label_25.setObjectName(u"label_25")
        self.label_25.setGeometry(QRect(130, 40, 31, 16))
        self.lcdNumber_2 = QLCDNumber(self.afficheur_2)
        self.lcdNumber_2.setObjectName(u"lcdNumber_2")
        self.lcdNumber_2.setGeometry(QRect(0, 20, 121, 41))
        self.lcdNumber_2.setSmallDecimalPoint(False)
        self.afficheur_3 = QWidget(self.frame_9)
        self.afficheur_3.setObjectName(u"afficheur_3")
        self.afficheur_3.setGeometry(QRect(200, 10, 161, 61))
        self.label_28 = QLabel(self.afficheur_3)
        self.label_28.setObjectName(u"label_28")
        self.label_28.setGeometry(QRect(0, 0, 83, 16))
        self.label_29 = QLabel(self.afficheur_3)
        self.label_29.setObjectName(u"label_29")
        self.label_29.setGeometry(QRect(130, 40, 31, 16))
        self.lcdNumber_10 = QLCDNumber(self.afficheur_3)
        self.lcdNumber_10.setObjectName(u"lcdNumber_10")
        self.lcdNumber_10.setGeometry(QRect(0, 20, 121, 41))
        self.lcdNumber_10.setSmallDecimalPoint(False)
        self.label_53 = QLabel(self.Container_8)
        self.label_53.setObjectName(u"label_53")
        self.label_53.setGeometry(QRect(0, 0, 161, 16))
        self.listWidget_vacuum = QListWidget(self.Vide)
        self.listWidget_vacuum.setObjectName(u"listWidget_vacuum")
        self.listWidget_vacuum.setGeometry(QRect(20, 250, 1221, 521))
        self.listWidget_vacuum.setFrameShape(QFrame.Shape.Box)
        self.Container_9 = QWidget(self.Vide)
        self.Container_9.setObjectName(u"Container_9")
        self.Container_9.setGeometry(QRect(430, 20, 381, 111))
        self.frame_10 = QFrame(self.Container_9)
        self.frame_10.setObjectName(u"frame_10")
        self.frame_10.setGeometry(QRect(0, 20, 381, 91))
        self.frame_10.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame_10.setFrameShadow(QFrame.Shadow.Raised)
        self.afficheur_10 = QWidget(self.frame_10)
        self.afficheur_10.setObjectName(u"afficheur_10")
        self.afficheur_10.setGeometry(QRect(20, 10, 161, 61))
        self.label_30 = QLabel(self.afficheur_10)
        self.label_30.setObjectName(u"label_30")
        self.label_30.setGeometry(QRect(0, 0, 83, 16))
        self.label_31 = QLabel(self.afficheur_10)
        self.label_31.setObjectName(u"label_31")
        self.label_31.setGeometry(QRect(130, 40, 31, 16))
        self.lcdNumber_11 = QLCDNumber(self.afficheur_10)
        self.lcdNumber_11.setObjectName(u"lcdNumber_11")
        self.lcdNumber_11.setGeometry(QRect(0, 20, 121, 41))
        self.lcdNumber_11.setSmallDecimalPoint(False)
        self.afficheur_11 = QWidget(self.frame_10)
        self.afficheur_11.setObjectName(u"afficheur_11")
        self.afficheur_11.setGeometry(QRect(200, 10, 161, 61))
        self.label_32 = QLabel(self.afficheur_11)
        self.label_32.setObjectName(u"label_32")
        self.label_32.setGeometry(QRect(0, 0, 83, 16))
        self.label_33 = QLabel(self.afficheur_11)
        self.label_33.setObjectName(u"label_33")
        self.label_33.setGeometry(QRect(130, 40, 31, 16))
        self.lcdNumber_12 = QLCDNumber(self.afficheur_11)
        self.lcdNumber_12.setObjectName(u"lcdNumber_12")
        self.lcdNumber_12.setGeometry(QRect(0, 20, 121, 41))
        self.lcdNumber_12.setSmallDecimalPoint(False)
        self.label_54 = QLabel(self.Container_9)
        self.label_54.setObjectName(u"label_54")
        self.label_54.setGeometry(QRect(0, 0, 161, 16))
        self.Container_10 = QWidget(self.Vide)
        self.Container_10.setObjectName(u"Container_10")
        self.Container_10.setGeometry(QRect(840, 20, 303, 111))
        self.frame_11 = QFrame(self.Container_10)
        self.frame_11.setObjectName(u"frame_11")
        self.frame_11.setGeometry(QRect(0, 20, 303, 91))
        self.frame_11.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame_11.setFrameShadow(QFrame.Shadow.Raised)
        self.afficheur_12 = QWidget(self.frame_11)
        self.afficheur_12.setObjectName(u"afficheur_12")
        self.afficheur_12.setGeometry(QRect(20, 10, 161, 61))
        self.label_34 = QLabel(self.afficheur_12)
        self.label_34.setObjectName(u"label_34")
        self.label_34.setGeometry(QRect(0, 0, 83, 16))
        self.label_35 = QLabel(self.afficheur_12)
        self.label_35.setObjectName(u"label_35")
        self.label_35.setGeometry(QRect(130, 40, 22, 16))
        self.lcdNumber_13 = QLCDNumber(self.afficheur_12)
        self.lcdNumber_13.setObjectName(u"lcdNumber_13")
        self.lcdNumber_13.setGeometry(QRect(0, 20, 121, 41))
        self.lcdNumber_13.setSmallDecimalPoint(False)
        self.afficheur_13 = QWidget(self.frame_11)
        self.afficheur_13.setObjectName(u"afficheur_13")
        self.afficheur_13.setGeometry(QRect(200, 30, 83, 44))
        self.label_36 = QLabel(self.afficheur_13)
        self.label_36.setObjectName(u"label_36")
        self.label_36.setGeometry(QRect(0, 0, 33, 16))
        self.pushButton_LogOnOff_2 = QPushButton(self.afficheur_13)
        self.pushButton_LogOnOff_2.setObjectName(u"pushButton_LogOnOff_2")
        self.pushButton_LogOnOff_2.setGeometry(QRect(0, 20, 75, 24))
        self.pushButton_LogOnOff_2.setCheckable(True)
        self.pushButton_LogOnOff_2.setChecked(True)
        self.label_58 = QLabel(self.Container_10)
        self.label_58.setObjectName(u"label_58")
        self.label_58.setGeometry(QRect(0, 0, 161, 16))
        self.tabWidget.addTab(self.Vide, "")
        self.Eau = QWidget()
        self.Eau.setObjectName(u"Eau")
        self.label_23 = QLabel(self.Eau)
        self.label_23.setObjectName(u"label_23")
        self.label_23.setGeometry(QRect(630, 130, 601, 531))
        self.label_23.setPixmap(QPixmap(u":/newPrefix/Schema Eau.png"))
        self.tabWidget.addTab(self.Eau, "")
        self.Paramtres = QWidget()
        self.Paramtres.setObjectName(u"Paramtres")
        self.widget = QWidget(self.Paramtres)
        self.widget.setObjectName(u"widget")
        self.widget.setGeometry(QRect(20, 20, 621, 284))
        self.frame = QFrame(self.widget)
        self.frame.setObjectName(u"frame")
        self.frame.setGeometry(QRect(0, 20, 621, 264))
        self.frame.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QFrame.Shadow.Raised)
        self.label_43 = QLabel(self.frame)
        self.label_43.setObjectName(u"label_43")
        self.label_43.setGeometry(QRect(10, 10, 99, 16))
        self.numInput_14 = QWidget(self.frame)
        self.numInput_14.setObjectName(u"numInput_14")
        self.numInput_14.setGeometry(QRect(10, 70, 149, 61))
        self.label_56 = QLabel(self.numInput_14)
        self.label_56.setObjectName(u"label_56")
        self.label_56.setGeometry(QRect(0, 0, 149, 16))
        self.spinBox_logFrequency = QSpinBox(self.numInput_14)
        self.spinBox_logFrequency.setObjectName(u"spinBox_logFrequency")
        self.spinBox_logFrequency.setGeometry(QRect(0, 20, 121, 41))
        self.spinBox_logFrequency.setButtonSymbols(QAbstractSpinBox.ButtonSymbols.UpDownArrows)
        self.spinBox_logFrequency.setMinimum(1)
        self.label_57 = QLabel(self.numInput_14)
        self.label_57.setObjectName(u"label_57")
        self.label_57.setGeometry(QRect(130, 40, 19, 16))
        self.numInput_13 = QWidget(self.frame)
        self.numInput_13.setObjectName(u"numInput_13")
        self.numInput_13.setGeometry(QRect(10, 140, 148, 61))
        self.label_52 = QLabel(self.numInput_13)
        self.label_52.setObjectName(u"label_52")
        self.label_52.setGeometry(QRect(0, 0, 139, 16))
        self.spinBox_fileSizeLimit = QSpinBox(self.numInput_13)
        self.spinBox_fileSizeLimit.setObjectName(u"spinBox_fileSizeLimit")
        self.spinBox_fileSizeLimit.setGeometry(QRect(0, 20, 121, 41))
        self.spinBox_fileSizeLimit.setButtonSymbols(QAbstractSpinBox.ButtonSymbols.UpDownArrows)
        self.spinBox_fileSizeLimit.setMinimum(1)
        self.label_55 = QLabel(self.numInput_13)
        self.label_55.setObjectName(u"label_55")
        self.label_55.setGeometry(QRect(130, 40, 18, 16))
        self.label_44 = QLabel(self.frame)
        self.label_44.setObjectName(u"label_44")
        self.label_44.setGeometry(QRect(10, 210, 197, 16))
        self.pushButton_LogOnOff = QPushButton(self.frame)
        self.pushButton_LogOnOff.setObjectName(u"pushButton_LogOnOff")
        self.pushButton_LogOnOff.setGeometry(QRect(10, 230, 75, 24))
        self.pushButton_LogOnOff.setCheckable(True)
        self.pushButton_LogOnOff.setChecked(True)
        self.textBrowser_logPath = QTextBrowser(self.frame)
        self.textBrowser_logPath.setObjectName(u"textBrowser_logPath")
        self.textBrowser_logPath.setGeometry(QRect(10, 30, 601, 31))
        self.textBrowser_logPath.setFrameShape(QFrame.Shape.Box)
        self.textBrowser_logPath.setFrameShadow(QFrame.Shadow.Sunken)
        self.textBrowser_logPath.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAsNeeded)
        self.label_logPath = QLabel(self.frame)
        self.label_logPath.setObjectName(u"label_logPath")
        self.label_logPath.setGeometry(QRect(20, 40, 581, 16))
        self.label_logPath.setScaledContents(False)
        self.label = QLabel(self.widget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(0, 0, 161, 16))
        self.widget_2 = QWidget(self.Paramtres)
        self.widget_2.setObjectName(u"widget_2")
        self.widget_2.setGeometry(QRect(700, 20, 621, 284))
        self.frame_5 = QFrame(self.widget_2)
        self.frame_5.setObjectName(u"frame_5")
        self.frame_5.setGeometry(QRect(0, 20, 621, 264))
        self.frame_5.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame_5.setFrameShadow(QFrame.Shadow.Raised)
        self.label_51 = QLabel(self.frame_5)
        self.label_51.setObjectName(u"label_51")
        self.label_51.setGeometry(QRect(10, 10, 171, 16))
        self.pushButton_Refresh = QPushButton(self.frame_5)
        self.pushButton_Refresh.setObjectName(u"pushButton_Refresh")
        self.pushButton_Refresh.setGeometry(QRect(510, 30, 80, 24))
        self.pushButton_Refresh.setCheckable(False)
        self.pushButton_Refresh.setChecked(False)
        self.listWidget_PortList = QListWidget(self.frame_5)
        self.listWidget_PortList.setObjectName(u"listWidget_PortList")
        self.listWidget_PortList.setGeometry(QRect(10, 31, 481, 221))
        self.listWidget_PortList.setFrameShape(QFrame.Shape.Box)
        self.label_22 = QLabel(self.widget_2)
        self.label_22.setObjectName(u"label_22")
        self.label_22.setGeometry(QRect(0, 0, 161, 16))
        icon = QIcon(QIcon.fromTheme(u"applications-development"))
        self.tabWidget.addTab(self.Paramtres, icon, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        self.tabWidget.setCurrentIndex(4)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.label_2.setText("")
        self.label_37.setText(QCoreApplication.translate("MainWindow", u"D\u00e9bit Argon", None))
        self.label_38.setText(QCoreApplication.translate("MainWindow", u"ml/min", None))
        self.label_39.setText(QCoreApplication.translate("MainWindow", u"Diaphragme", None))
        self.pushButton_Diaphragme.setText(QCoreApplication.translate("MainWindow", u"On", None))
        self.label_59.setText(QCoreApplication.translate("MainWindow", u"G\u00e9n\u00e9ral", None))
        self.label_26.setText(QCoreApplication.translate("MainWindow", u"R\u00e9glage Arc", None))
        self.radioButton_C1S1_2.setText(QCoreApplication.translate("MainWindow", u"Tension", None))
        self.radioButton_C1S2_2.setText(QCoreApplication.translate("MainWindow", u"Courant", None))
        self.label_66.setText(QCoreApplication.translate("MainWindow", u"mA", None))
        self.label_67.setText(QCoreApplication.translate("MainWindow", u"KV", None))
        self.label_40.setText(QCoreApplication.translate("MainWindow", u"Tension effective Arc", None))
        self.label_41.setText(QCoreApplication.translate("MainWindow", u"KV", None))
        self.label_42.setText(QCoreApplication.translate("MainWindow", u"Courant effectif Arc", None))
        self.label_60.setText(QCoreApplication.translate("MainWindow", u"mA", None))
        self.label_27.setText(QCoreApplication.translate("MainWindow", u"D\u00e9bit gaz ml/min", None))
        self.label_61.setText(QCoreApplication.translate("MainWindow", u"Courant effectif Filament", None))
        self.label_62.setText(QCoreApplication.translate("MainWindow", u"mA", None))
        self.label_68.setText(QCoreApplication.translate("MainWindow", u"Courant Filament", None))
        self.label_69.setText(QCoreApplication.translate("MainWindow", u"\u00b5A", None))
        self.label_64.setText(QCoreApplication.translate("MainWindow", u"Source", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Injection), QCoreApplication.translate("MainWindow", u"Injection", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"Courant bobine", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"\u00b5A", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"Courant effectif", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"\u00b5A", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"Bobine", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Aimant), QCoreApplication.translate("MainWindow", u"Aimant", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"Amplificateur", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"\u00b5A", None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"Tension cr\u00eate", None))
        self.label_11.setText(QCoreApplication.translate("MainWindow", u"KV", None))
        self.label_13.setText(QCoreApplication.translate("MainWindow", u"Position effective piston d'accord", None))
        self.label_14.setText(QCoreApplication.translate("MainWindow", u"Position piston d'accord", None))
        self.label_12.setText(QCoreApplication.translate("MainWindow", u"RF", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.RF), QCoreApplication.translate("MainWindow", u"RF", None))
        self.label_19.setText(QCoreApplication.translate("MainWindow", u"Cible 1", None))
        self.label_20.setText(QCoreApplication.translate("MainWindow", u"Cible 2", None))
        self.radioButton_C1S1.setText(QCoreApplication.translate("MainWindow", u"Stripper 1", None))
        self.radioButton_C1S2.setText(QCoreApplication.translate("MainWindow", u"Stripper 2", None))
        self.radioButton_C1S3.setText(QCoreApplication.translate("MainWindow", u"Stripper 3", None))
        self.label_15.setText(QCoreApplication.translate("MainWindow", u"Rayon canne cible 1", None))
        self.label_16.setText(QCoreApplication.translate("MainWindow", u"cm", None))
        self.label_17.setText(QCoreApplication.translate("MainWindow", u"Rayon canne cible 2", None))
        self.label_18.setText(QCoreApplication.translate("MainWindow", u"cm", None))
        self.radioButton_C2S1.setText(QCoreApplication.translate("MainWindow", u"Stripper 1", None))
        self.radioButton_C2S2.setText(QCoreApplication.translate("MainWindow", u"Stripper 2", None))
        self.radioButton_C2S3.setText(QCoreApplication.translate("MainWindow", u"Stripper 3", None))
        self.label_48.setText(QCoreApplication.translate("MainWindow", u"\u00b5A", None))
        self.label_49.setText(QCoreApplication.translate("MainWindow", u"\u00b5A", None))
        self.label_50.setText(QCoreApplication.translate("MainWindow", u"\u00b5A", None))
        self.label_45.setText(QCoreApplication.translate("MainWindow", u"\u00b5A", None))
        self.label_46.setText(QCoreApplication.translate("MainWindow", u"\u00b5A", None))
        self.label_47.setText(QCoreApplication.translate("MainWindow", u"\u00b5A", None))
        self.label_21.setText(QCoreApplication.translate("MainWindow", u"Cibles", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Exxtraction), QCoreApplication.translate("MainWindow", u"Extraction", None))
        self.label_24.setText(QCoreApplication.translate("MainWindow", u"Sonde 1", None))
        self.label_25.setText(QCoreApplication.translate("MainWindow", u"mbar", None))
        self.label_28.setText(QCoreApplication.translate("MainWindow", u"Sonde 2", None))
        self.label_29.setText(QCoreApplication.translate("MainWindow", u"mbar", None))
        self.label_53.setText(QCoreApplication.translate("MainWindow", u"Vide primaire", None))
        self.label_30.setText(QCoreApplication.translate("MainWindow", u"Sonde 1", None))
        self.label_31.setText(QCoreApplication.translate("MainWindow", u"mbar", None))
        self.label_32.setText(QCoreApplication.translate("MainWindow", u"Sonde 2", None))
        self.label_33.setText(QCoreApplication.translate("MainWindow", u"mbar", None))
        self.label_54.setText(QCoreApplication.translate("MainWindow", u"Vide secondaire", None))
        self.label_34.setText(QCoreApplication.translate("MainWindow", u"Vitesse", None))
        self.label_35.setText(QCoreApplication.translate("MainWindow", u"rpm", None))
        self.label_36.setText(QCoreApplication.translate("MainWindow", u"Status", None))
        self.pushButton_LogOnOff_2.setText(QCoreApplication.translate("MainWindow", u"On", None))
        self.label_58.setText(QCoreApplication.translate("MainWindow", u"Pompe", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Vide), QCoreApplication.translate("MainWindow", u"Vide", None))
        self.label_23.setText("")
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Eau), QCoreApplication.translate("MainWindow", u"Eau", None))
        self.label_43.setText(QCoreApplication.translate("MainWindow", u"Chemin du dossier", None))
        self.label_56.setText(QCoreApplication.translate("MainWindow", u"Fr\u00e9quence d'enregistrement", None))
        self.label_57.setText(QCoreApplication.translate("MainWindow", u"Sec", None))
        self.label_52.setText(QCoreApplication.translate("MainWindow", u"Limite de taille par fichiers", None))
        self.label_55.setText(QCoreApplication.translate("MainWindow", u"Mb", None))
        self.label_44.setText(QCoreApplication.translate("MainWindow", u"Activer l'enregistrement des donn\u00e9es", None))
        self.pushButton_LogOnOff.setText(QCoreApplication.translate("MainWindow", u"On", None))
        self.textBrowser_logPath.setDocumentTitle("")
        self.label_logPath.setText(QCoreApplication.translate("MainWindow", u"Path", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"Enregistrement des donn\u00e9es", None))
        self.label_51.setText(QCoreApplication.translate("MainWindow", u"Ports disponibles", None))
        self.pushButton_Refresh.setText(QCoreApplication.translate("MainWindow", u"Rafraichir", None))
        self.label_22.setText(QCoreApplication.translate("MainWindow", u"Appareils connect\u00e9s", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Paramtres), QCoreApplication.translate("MainWindow", u"Param\u00e8tres", None))
    # retranslateUi

